import Head from "next/head";
import Overlay from "components/overlay";
import styles from "../styles/Home.module.scss";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>CONTENT CHEMICS - Representation and Management</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Overlay
        leftText={"Content"}
        rightText={"Chemics"}
        animationTexts={["Representation", "Management", "Development"]}
      />
    </div>
  );
}
